#define RACCOMPOUNDDISPOSABLE_ADDED_ENABLED() 0
#define RACCOMPOUNDDISPOSABLE_ADDED(a,b,c) do {} while(0)
#define RACCOMPOUNDDISPOSABLE_REMOVED_ENABLED() 0
#define RACCOMPOUNDDISPOSABLE_REMOVED(a,b,c) do {} while(0)
